export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const SET_LOCATION = 'SET_LOCATION';
export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';
export const REMOVE_FROM_FAVORITE = 'REMOVE_FROM_FAVORITE';
export const SET_FAVORITES = 'SET_FAVORITES';
export const SET_FAVORITES_KEYS = 'SET_FAVORITES_KEYS';
